name: Lint Python Code

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install pipenv
      run: |
        python -m pip install --upgrade pipenv wheel
    - name: Build and install
      run: |
        pipenv install --deploy --dev
    - name: Scan for code quality
      run: |
        pipenv run python -m pylint templatizer examples tests
        pipenv run python -m pycodestyle --max-line-length=100 --exclude=gen.py templatizer examples tests
        pipenv run python -m flake8 templatizer examples tests
        pipenv run python -m black --check templatizer examples tests
        pipenv run python -m mypy templatizer examples tests
        pipenv run python -m isort -rc templatizer examples tests -c --diff
